# MSIX Conversion Recipe Template
# MSIX Conversion Template
PackageName: JRE

PackageVersion: 1.8.0_301-b09

PublisherName: Oracle

EligibleForConversion: Yes

ConversionStatus: Successful - No Fix Required

Edition: Windows 10 Enterprise

MinimumOSVersion: 20H2

MinimumOSBuild: 19042.685

Architecture: 64

MSIXConversionToolVersion: 1.2020.1219.0 

TemplateVersion: 1.0.0
