# MSIX Conversion Template
PackageName: USB Disk Security123

PackageVersion: 6.9.0.0

PublisherName: Zbshareware Lab

EligibleForConversion: Yes

ConversionStatus: Successful - No Fix Required

Edition: Windows 10 Enterprise Evaluation

MinimumOSVersion: 20H2

MinimumOSBuild: 19043.1237

Architecture: 64

MSIXConversionToolVersion: 1.2021.709.0

TemplateVersion: 1.0.0
