# MSIX Conversion Template
PackageName: Bit Defender Total Security

PackageVersion: 26.0.7.34

PublisherName:

EligibleForConversion: No - Driver Required

ConversionStatus: Not Eligible

AdditionalComments:
  - App Installs 12 drivers which are not supported by MSIX Packaging Tool

Edition: Windows 10 Enterprise Evaluation

MinimumOSVersion: 20H2

MinimumOSBuild: 19042.685

Architecture: 64

MSIXConversionToolVersion: 1.2020.1219.0

TemplateVersion: 1.0.0
